//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetyraSiguri.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DetyraSiguri.Lang.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string btnDekript {
            get {
                return ResourceManager.GetString("btnDekript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string btnEnkript {
            get {
                return ResourceManager.GetString("btnEnkript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string btnGjuha {
            get {
                return ResourceManager.GetString("btnGjuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnMbyll {
            get {
                return ResourceManager.GetString("btnMbyll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string btnOpsion {
            get {
                return ResourceManager.GetString("btnOpsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string gabimi {
            get {
                return ResourceManager.GetString("gabimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about the Project.
        /// </summary>
        internal static string grInfo {
            get {
                return ResourceManager.GetString("grInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;Enkriptimi me 3DES&quot; worked in Internet Security 
        ///by students and our prof.Ilir Murturi as our supervisor: .
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type of Encryption:.
        /// </summary>
        internal static string lblLlojiEnkr {
            get {
                return ResourceManager.GetString("lblLlojiEnkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File:.
        /// </summary>
        internal static string lblZgjedhFajllin {
            get {
                return ResourceManager.GetString("lblZgjedhFajllin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the Key of Encryption.
        /// </summary>
        internal static string titulliNeRuajtjeTeCelsit {
            get {
                return ResourceManager.GetString("titulliNeRuajtjeTeCelsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string tstAnglisht {
            get {
                return ResourceManager.GetString("tstAnglisht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        internal static string tstShqip {
            get {
                return ResourceManager.GetString("tstShqip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption finished successfully, for so long:.
        /// </summary>
        internal static string tstStatusiD {
            get {
                return ResourceManager.GetString("tstStatusiD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption finished successfully, for so long: .
        /// </summary>
        internal static string tstStatusiE {
            get {
                return ResourceManager.GetString("tstStatusiE", resourceCulture);
            }
        }
    }
}
